spring.application.name=coffee-hrm
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CoffeeHRM;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=sa

server.port=8081
server.servlet.context-path=/

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
